# Generated by Django 5.0.1 on 2024-02-22 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produtos",
            fields=[
                ("id_produto", models.AutoField(primary_key=True, serialize=False)),
                ("id_efator", models.IntegerField()),
                ("descricao", models.CharField(max_length=100)),
                ("grupo", models.CharField(max_length=100)),
                ("custocompra", models.DecimalField(decimal_places=2, max_digits=10)),
                ("precovenda", models.DecimalField(decimal_places=2, max_digits=10)),
                ("classificadcaofiscal", models.CharField(max_length=100)),
                ("fornecedor", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="CodigoBarras",
            fields=[
                (
                    "id_codigobarras",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("codigobarras", models.CharField(max_length=100)),
                (
                    "id_produto",
                    models.ForeignKey(
                        db_column="id_produto",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.produtos",
                    ),
                ),
            ],
        ),
    ]
