# Generated by Django 5.0.1 on 2024-02-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_produtos_fornecedor_alter_produtos_grupo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produtos",
            name="custocompra",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
